build: false

environment:
  matrix:
    - PYTHON: "C:\\Python27-x64"

    - PYTHON: "C:\\Python35-x64"

init:
  - SET PATH=%PYTHON%;%PATH%
  - python -c "import sys;sys.stdout.write(sys.version)"

install:
  - python -m pip install nose

test_script:
  - python -m nose -s
